/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.96.
*        Compiled Jul 19 2005, 13:50:35
*          (c) 2002-2005  Micrium, Inc.
  www.micrium.com

  (c) 1998-2005  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: icon_mean_cycle
* Dimensions:  45 * 32
* NumColors:   0
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif


static GUI_CONST_STORAGE unsigned char acicon_mean_cycle[] = {
  /* RLE: 023 Pixels @ 000,000*/ 23, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 023,000*/ 1, 0x59, 0xCE, 
  /* RLE: 043 Pixels @ 024,000*/ 43, 0x45, 0x21, 
  /* ABS: 003 Pixels @ 022,001*/ 0, 3, 0x59, 0xCE, 0x45, 0x21, 0x59, 0xCE, 
  /* RLE: 041 Pixels @ 025,001*/ 41, 0x45, 0x21, 
  /* ABS: 005 Pixels @ 021,002*/ 0, 5, 0x59, 0xCE, 0x45, 0x21, 0x45, 0x21, 0x45, 0x21, 0x59, 0xCE, 
  /* RLE: 040 Pixels @ 026,002*/ 40, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 021,003*/ 1, 0x59, 0xCE, 
  /* RLE: 004 Pixels @ 022,003*/ 4, 0x45, 0x21, 
  /* RLE: 005 Pixels @ 026,003*/ 5, 0x59, 0xCE, 
  /* RLE: 035 Pixels @ 031,003*/ 35, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 021,004*/ 1, 0x59, 0xCE, 
  /* RLE: 008 Pixels @ 022,004*/ 8, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 030,004*/ 1, 0x59, 0xCE, 
  /* RLE: 035 Pixels @ 031,004*/ 35, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 021,005*/ 1, 0x59, 0xCE, 
  /* RLE: 008 Pixels @ 022,005*/ 8, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 030,005*/ 1, 0x59, 0xCE, 
  /* RLE: 035 Pixels @ 031,005*/ 35, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 021,006*/ 1, 0x59, 0xCE, 
  /* RLE: 008 Pixels @ 022,006*/ 8, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 030,006*/ 1, 0x59, 0xCE, 
  /* RLE: 035 Pixels @ 031,006*/ 35, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 021,007*/ 1, 0x59, 0xCE, 
  /* RLE: 008 Pixels @ 022,007*/ 8, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 030,007*/ 1, 0x59, 0xCE, 
  /* RLE: 035 Pixels @ 031,007*/ 35, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 021,008*/ 1, 0x59, 0xCE, 
  /* RLE: 008 Pixels @ 022,008*/ 8, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 030,008*/ 1, 0x59, 0xCE, 
  /* RLE: 023 Pixels @ 031,008*/ 23, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 009,009*/ 1, 0x20, 0xFC, 
  /* RLE: 005 Pixels @ 010,009*/ 5, 0x45, 0x21, 
  /* ABS: 019 Pixels @ 015,009*/ 0, 19, 0x20, 0xFC, 0x20, 0xFC, 0x45, 0x21, 0x20, 0xFC, 0x20, 0xFC, 0x45, 0x21, 0x59, 0xCE, 0x45, 0x21, 0x20, 0xFC, 0x20, 0xFC, 0x45, 0x21, 0x20, 0xFC, 0x20, 0xFC, 0x20, 0xFC, 0x45, 0x21, 0x59, 0xCE, 0x45, 0x21, 
        0x20, 0xFC, 0x20, 0xFC, 
  /* RLE: 019 Pixels @ 034,009*/ 19, 0x45, 0x21, 
  /* RLE: 003 Pixels @ 008,010*/ 3, 0x20, 0xFC, 
  /* RLE: 010 Pixels @ 011,010*/ 10, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 021,010*/ 1, 0x59, 0xCE, 
  /* RLE: 008 Pixels @ 022,010*/ 8, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 030,010*/ 1, 0x59, 0xCE, 
  /* RLE: 021 Pixels @ 031,010*/ 21, 0x45, 0x21, 
  /* RLE: 005 Pixels @ 007,011*/ 5, 0x20, 0xFC, 
  /* RLE: 009 Pixels @ 012,011*/ 9, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 021,011*/ 1, 0x59, 0xCE, 
  /* RLE: 008 Pixels @ 022,011*/ 8, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 030,011*/ 1, 0x59, 0xCE, 
  /* RLE: 023 Pixels @ 031,011*/ 23, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 009,012*/ 1, 0x20, 0xFC, 
  /* RLE: 011 Pixels @ 010,012*/ 11, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 021,012*/ 1, 0x59, 0xCE, 
  /* RLE: 008 Pixels @ 022,012*/ 8, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 030,012*/ 1, 0x59, 0xCE, 
  /* RLE: 023 Pixels @ 031,012*/ 23, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 009,013*/ 1, 0x20, 0xFC, 
  /* RLE: 011 Pixels @ 010,013*/ 11, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 021,013*/ 1, 0x59, 0xCE, 
  /* RLE: 008 Pixels @ 022,013*/ 8, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 030,013*/ 1, 0x59, 0xCE, 
  /* RLE: 023 Pixels @ 031,013*/ 23, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 009,014*/ 1, 0x20, 0xFC, 
  /* RLE: 011 Pixels @ 010,014*/ 11, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 021,014*/ 1, 0x59, 0xCE, 
  /* RLE: 008 Pixels @ 022,014*/ 8, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 030,014*/ 1, 0x59, 0xCE, 
  /* RLE: 023 Pixels @ 031,014*/ 23, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 009,015*/ 1, 0x20, 0xFC, 
  /* RLE: 011 Pixels @ 010,015*/ 11, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 021,015*/ 1, 0x59, 0xCE, 
  /* RLE: 008 Pixels @ 022,015*/ 8, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 030,015*/ 1, 0x59, 0xCE, 
  /* RLE: 023 Pixels @ 031,015*/ 23, 0x45, 0x21, 
  /* ABS: 004 Pixels @ 009,016*/ 0, 4, 0x20, 0xFC, 0x45, 0x21, 0x45, 0x21, 0x45, 0x21, 
  /* RLE: 004 Pixels @ 013,016*/ 4, 0x59, 0xCE, 
  /* RLE: 004 Pixels @ 017,016*/ 4, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 021,016*/ 1, 0x59, 0xCE, 
  /* RLE: 008 Pixels @ 022,016*/ 8, 0x45, 0x21, 
  /* RLE: 005 Pixels @ 030,016*/ 5, 0x59, 0xCE, 
  /* RLE: 019 Pixels @ 035,016*/ 19, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 009,017*/ 1, 0x20, 0xFC, 
  /* RLE: 007 Pixels @ 010,017*/ 7, 0x45, 0x21, 
  /* ABS: 005 Pixels @ 017,017*/ 0, 5, 0x59, 0xCE, 0x45, 0x21, 0x45, 0x21, 0x45, 0x21, 0x59, 0xCE, 
  /* RLE: 032 Pixels @ 022,017*/ 32, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 009,018*/ 1, 0x20, 0xFC, 
  /* RLE: 008 Pixels @ 010,018*/ 8, 0x45, 0x21, 
  /* ABS: 003 Pixels @ 018,018*/ 0, 3, 0x59, 0xCE, 0x45, 0x21, 0x59, 0xCE, 
  /* RLE: 033 Pixels @ 021,018*/ 33, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 009,019*/ 1, 0x20, 0xFC, 
  /* RLE: 009 Pixels @ 010,019*/ 9, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 019,019*/ 1, 0x59, 0xCE, 
  /* RLE: 034 Pixels @ 020,019*/ 34, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 009,020*/ 1, 0x20, 0xFC, 
  /* RLE: 044 Pixels @ 010,020*/ 44, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 009,021*/ 1, 0x20, 0xFC, 
  /* RLE: 044 Pixels @ 010,021*/ 44, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 009,022*/ 1, 0x20, 0xFC, 
  /* RLE: 028 Pixels @ 010,022*/ 28, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 038,022*/ 1, 0x20, 0xFC, 
  /* RLE: 013 Pixels @ 039,022*/ 13, 0x45, 0x21, 
  /* RLE: 005 Pixels @ 007,023*/ 5, 0x20, 0xFC, 
  /* RLE: 026 Pixels @ 012,023*/ 26, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 038,023*/ 1, 0x20, 0xFC, 
  /* RLE: 029 Pixels @ 039,023*/ 29, 0x45, 0x21, 
  /* RLE: 003 Pixels @ 023,024*/ 3, 0x20, 0xFC, 
  /* ABS: 018 Pixels @ 026,024*/ 0, 18, 0x45, 0x21, 0x20, 0xFC, 0x45, 0x21, 0x45, 0x21, 0x45, 0x21, 0x20, 0xFC, 0x45, 0x21, 0x45, 0x21, 0x20, 0xFC, 0x20, 0xFC, 0x20, 0xFC, 0x45, 0x21, 0x20, 0xFC, 0x45, 0x21, 0x45, 0x21, 0x45, 0x21, 0x20, 0xFC, 
        0x20, 0xFC, 
  /* RLE: 023 Pixels @ 044,024*/ 23, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 022,025*/ 1, 0x20, 0xFC, 
  /* RLE: 004 Pixels @ 023,025*/ 4, 0x45, 0x21, 
  /* ABS: 007 Pixels @ 027,025*/ 0, 7, 0x20, 0xFC, 0x45, 0x21, 0x45, 0x21, 0x45, 0x21, 0x20, 0xFC, 0x45, 0x21, 0x20, 0xFC, 
  /* RLE: 004 Pixels @ 034,025*/ 4, 0x45, 0x21, 
  /* ABS: 007 Pixels @ 038,025*/ 0, 7, 0x20, 0xFC, 0x45, 0x21, 0x45, 0x21, 0x20, 0xFC, 0x45, 0x21, 0x45, 0x21, 0x20, 0xFC, 
  /* RLE: 022 Pixels @ 000,026*/ 22, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 022,026*/ 1, 0x20, 0xFC, 
  /* RLE: 005 Pixels @ 023,026*/ 5, 0x45, 0x21, 
  /* ABS: 006 Pixels @ 028,026*/ 0, 6, 0x20, 0xFC, 0x45, 0x21, 0x20, 0xFC, 0x45, 0x21, 0x45, 0x21, 0x20, 0xFC, 
  /* RLE: 004 Pixels @ 034,026*/ 4, 0x45, 0x21, 
  /* ABS: 003 Pixels @ 038,026*/ 0, 3, 0x20, 0xFC, 0x45, 0x21, 0x45, 0x21, 
  /* RLE: 004 Pixels @ 041,026*/ 4, 0x20, 0xFC, 
  /* RLE: 022 Pixels @ 000,027*/ 22, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 022,027*/ 1, 0x20, 0xFC, 
  /* RLE: 005 Pixels @ 023,027*/ 5, 0x45, 0x21, 
  /* ABS: 006 Pixels @ 028,027*/ 0, 6, 0x20, 0xFC, 0x45, 0x21, 0x20, 0xFC, 0x45, 0x21, 0x45, 0x21, 0x20, 0xFC, 
  /* RLE: 004 Pixels @ 034,027*/ 4, 0x45, 0x21, 
  /* ABS: 004 Pixels @ 038,027*/ 0, 4, 0x20, 0xFC, 0x45, 0x21, 0x45, 0x21, 0x20, 0xFC, 
  /* RLE: 025 Pixels @ 042,027*/ 25, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 022,028*/ 1, 0x20, 0xFC, 
  /* RLE: 005 Pixels @ 023,028*/ 5, 0x45, 0x21, 
  /* ABS: 006 Pixels @ 028,028*/ 0, 6, 0x20, 0xFC, 0x45, 0x21, 0x20, 0xFC, 0x45, 0x21, 0x45, 0x21, 0x20, 0xFC, 
  /* RLE: 004 Pixels @ 034,028*/ 4, 0x45, 0x21, 
  /* ABS: 004 Pixels @ 038,028*/ 0, 4, 0x20, 0xFC, 0x45, 0x21, 0x45, 0x21, 0x20, 0xFC, 
  /* RLE: 026 Pixels @ 042,028*/ 26, 0x45, 0x21, 
  /* RLE: 003 Pixels @ 023,029*/ 3, 0x20, 0xFC, 
  /* RLE: 003 Pixels @ 026,029*/ 3, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 029,029*/ 1, 0x20, 0xFC, 
  /* RLE: 004 Pixels @ 030,029*/ 4, 0x45, 0x21, 
  /* RLE: 003 Pixels @ 034,029*/ 3, 0x20, 0xFC, 
  /* ABS: 008 Pixels @ 037,029*/ 0, 8, 0x45, 0x21, 0x20, 0xFC, 0x45, 0x21, 0x45, 0x21, 0x45, 0x21, 0x20, 0xFC, 0x20, 0xFC, 0x20, 0xFC, 
  /* RLE: 029 Pixels @ 000,030*/ 29, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 029,030*/ 1, 0x20, 0xFC, 
  /* RLE: 042 Pixels @ 030,030*/ 42, 0x45, 0x21, 
  /* ABS: 002 Pixels @ 027,031*/ 0, 2, 0x20, 0xFC, 0x20, 0xFC, 
  /* RLE: 016 Pixels @ 029,031*/ 16, 0x45, 0x21, 


  0};  /* 392 for 1440 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmicon_mean_cycle = {
  45, /* XSize */
  32, /* YSize */
  90, /* BytesPerLine */
  16, /* BitsPerPixel */
  (unsigned char *)acicon_mean_cycle,  /* Pointer to picture data */
  NULL  /* Pointer to palette */
 ,GUI_DRAW_RLEM16
};

/* *** End of file *** */
