/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.96.
*        Compiled Jul 19 2005, 13:50:35
*          (c) 2002-2005  Micrium, Inc.
  www.micrium.com

  (c) 1998-2005  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: icon_dc_rms_fs
* Dimensions:  45 * 32
* NumColors:   0
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif


static GUI_CONST_STORAGE unsigned char acicon_dc_rms_fs[] = {
  /* RLE: 018 Pixels @ 000,000*/ 18, 0x45, 0x21, 
  /* RLE: 003 Pixels @ 018,000*/ 3, 0x59, 0xCE, 
  /* RLE: 041 Pixels @ 021,000*/ 41, 0x45, 0x21, 
  /* ABS: 005 Pixels @ 017,001*/ 0, 5, 0x59, 0xCE, 0xCB, 0x52, 0xCB, 0x52, 0xCB, 0x52, 0x59, 0xCE, 
  /* RLE: 040 Pixels @ 022,001*/ 40, 0x45, 0x21, 
  /* ABS: 005 Pixels @ 017,002*/ 0, 5, 0x59, 0xCE, 0xCB, 0x52, 0xCB, 0x52, 0xCB, 0x52, 0x59, 0xCE, 
  /* RLE: 033 Pixels @ 022,002*/ 33, 0x45, 0x21, 
  /* ABS: 025 Pixels @ 010,003*/ 0, 25, 0x20, 0xFC, 0x45, 0x21, 0x45, 0x21, 0x20, 0xFC, 0x20, 0xFC, 0x45, 0x21, 0x59, 0xCE, 0x45, 0x21, 0x20, 0xFC, 0x20, 0xFC, 0x20, 0xFC, 0x45, 0x21, 0x59, 0xCE, 0x45, 0x21, 0x20, 0xFC, 0x20, 0xFC, 0x45, 0x21, 
        0x20, 0xFC, 0x20, 0xFC, 0x45, 0x21, 0x20, 0xFC, 0x20, 0xFC, 0x45, 0x21, 0x20, 0xFC, 0x20, 0xFC, 
  /* RLE: 019 Pixels @ 035,003*/ 19, 0x45, 0x21, 
  /* RLE: 003 Pixels @ 009,004*/ 3, 0x20, 0xFC, 
  /* RLE: 004 Pixels @ 012,004*/ 4, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 016,004*/ 1, 0x59, 0xCE, 
  /* RLE: 005 Pixels @ 017,004*/ 5, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 022,004*/ 1, 0x59, 0xCE, 
  /* RLE: 030 Pixels @ 023,004*/ 30, 0x45, 0x21, 
  /* RLE: 005 Pixels @ 008,005*/ 5, 0x20, 0xFC, 
  /* RLE: 003 Pixels @ 013,005*/ 3, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 016,005*/ 1, 0x59, 0xCE, 
  /* RLE: 005 Pixels @ 017,005*/ 5, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 022,005*/ 1, 0x59, 0xCE, 
  /* RLE: 032 Pixels @ 023,005*/ 32, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 010,006*/ 1, 0x20, 0xFC, 
  /* RLE: 004 Pixels @ 011,006*/ 4, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 015,006*/ 1, 0x59, 0xCE, 
  /* RLE: 007 Pixels @ 016,006*/ 7, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 023,006*/ 1, 0x59, 0xCE, 
  /* RLE: 031 Pixels @ 024,006*/ 31, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 010,007*/ 1, 0x20, 0xFC, 
  /* RLE: 004 Pixels @ 011,007*/ 4, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 015,007*/ 1, 0x59, 0xCE, 
  /* RLE: 007 Pixels @ 016,007*/ 7, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 023,007*/ 1, 0x59, 0xCE, 
  /* RLE: 031 Pixels @ 024,007*/ 31, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 010,008*/ 1, 0x20, 0xFC, 
  /* RLE: 004 Pixels @ 011,008*/ 4, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 015,008*/ 1, 0x59, 0xCE, 
  /* RLE: 007 Pixels @ 016,008*/ 7, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 023,008*/ 1, 0x59, 0xCE, 
  /* RLE: 031 Pixels @ 024,008*/ 31, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 010,009*/ 1, 0x20, 0xFC, 
  /* RLE: 004 Pixels @ 011,009*/ 4, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 015,009*/ 1, 0x59, 0xCE, 
  /* RLE: 007 Pixels @ 016,009*/ 7, 0x45, 0x21, 
  /* ABS: 002 Pixels @ 023,009*/ 0, 2, 0x59, 0xCE, 0x59, 0xCE, 
  /* RLE: 007 Pixels @ 025,009*/ 7, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 032,009*/ 1, 0x59, 0xCE, 
  /* RLE: 022 Pixels @ 033,009*/ 22, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 010,010*/ 1, 0x20, 0xFC, 
  /* RLE: 013 Pixels @ 011,010*/ 13, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 024,010*/ 1, 0x59, 0xCE, 
  /* RLE: 007 Pixels @ 025,010*/ 7, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 032,010*/ 1, 0x59, 0xCE, 
  /* RLE: 022 Pixels @ 033,010*/ 22, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 010,011*/ 1, 0x20, 0xFC, 
  /* RLE: 013 Pixels @ 011,011*/ 13, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 024,011*/ 1, 0x59, 0xCE, 
  /* RLE: 007 Pixels @ 025,011*/ 7, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 032,011*/ 1, 0x59, 0xCE, 
  /* RLE: 022 Pixels @ 033,011*/ 22, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 010,012*/ 1, 0x20, 0xFC, 
  /* RLE: 013 Pixels @ 011,012*/ 13, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 024,012*/ 1, 0x59, 0xCE, 
  /* RLE: 007 Pixels @ 025,012*/ 7, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 032,012*/ 1, 0x59, 0xCE, 
  /* RLE: 022 Pixels @ 033,012*/ 22, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 010,013*/ 1, 0x20, 0xFC, 
  /* RLE: 014 Pixels @ 011,013*/ 14, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 025,013*/ 1, 0x59, 0xCE, 
  /* RLE: 005 Pixels @ 026,013*/ 5, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 031,013*/ 1, 0x59, 0xCE, 
  /* RLE: 023 Pixels @ 032,013*/ 23, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 010,014*/ 1, 0x20, 0xFC, 
  /* RLE: 014 Pixels @ 011,014*/ 14, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 025,014*/ 1, 0x59, 0xCE, 
  /* RLE: 005 Pixels @ 026,014*/ 5, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 031,014*/ 1, 0x59, 0xCE, 
  /* RLE: 023 Pixels @ 032,014*/ 23, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 010,015*/ 1, 0x20, 0xFC, 
  /* RLE: 014 Pixels @ 011,015*/ 14, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 025,015*/ 1, 0x59, 0xCE, 
  /* RLE: 005 Pixels @ 026,015*/ 5, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 031,015*/ 1, 0x59, 0xCE, 
  /* RLE: 023 Pixels @ 032,015*/ 23, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 010,016*/ 1, 0x20, 0xFC, 
  /* RLE: 015 Pixels @ 011,016*/ 15, 0x45, 0x21, 
  /* ABS: 005 Pixels @ 026,016*/ 0, 5, 0x59, 0xCE, 0x45, 0x21, 0x45, 0x21, 0x45, 0x21, 0x59, 0xCE, 
  /* RLE: 024 Pixels @ 031,016*/ 24, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 010,017*/ 1, 0x20, 0xFC, 
  /* RLE: 015 Pixels @ 011,017*/ 15, 0x45, 0x21, 
  /* ABS: 005 Pixels @ 026,017*/ 0, 5, 0x59, 0xCE, 0x45, 0x21, 0x45, 0x21, 0x45, 0x21, 0x59, 0xCE, 
  /* RLE: 024 Pixels @ 031,017*/ 24, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 010,018*/ 1, 0x20, 0xFC, 
  /* RLE: 016 Pixels @ 011,018*/ 16, 0x45, 0x21, 
  /* RLE: 003 Pixels @ 027,018*/ 3, 0x59, 0xCE, 
  /* RLE: 025 Pixels @ 030,018*/ 25, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 010,019*/ 1, 0x20, 0xFC, 
  /* RLE: 044 Pixels @ 011,019*/ 44, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 010,020*/ 1, 0x20, 0xFC, 
  /* RLE: 044 Pixels @ 011,020*/ 44, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 010,021*/ 1, 0x20, 0xFC, 
  /* RLE: 044 Pixels @ 011,021*/ 44, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 010,022*/ 1, 0x20, 0xFC, 
  /* RLE: 042 Pixels @ 011,022*/ 42, 0x45, 0x21, 
  /* RLE: 005 Pixels @ 008,023*/ 5, 0x20, 0xFC, 
  /* RLE: 067 Pixels @ 013,023*/ 67, 0x45, 0x21, 
  /* RLE: 004 Pixels @ 035,024*/ 4, 0x20, 0xFC, 
  /* RLE: 003 Pixels @ 039,024*/ 3, 0x45, 0x21, 
  /* RLE: 003 Pixels @ 042,024*/ 3, 0x20, 0xFC, 
  /* RLE: 035 Pixels @ 000,025*/ 35, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 035,025*/ 1, 0x20, 0xFC, 
  /* RLE: 005 Pixels @ 036,025*/ 5, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 041,025*/ 1, 0x20, 0xFC, 
  /* RLE: 038 Pixels @ 042,025*/ 38, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 035,026*/ 1, 0x20, 0xFC, 
  /* RLE: 005 Pixels @ 036,026*/ 5, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 041,026*/ 1, 0x20, 0xFC, 
  /* RLE: 038 Pixels @ 042,026*/ 38, 0x45, 0x21, 
  /* RLE: 004 Pixels @ 035,027*/ 4, 0x20, 0xFC, 
  /* RLE: 003 Pixels @ 039,027*/ 3, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 042,027*/ 1, 0x20, 0xFC, 
  /* RLE: 037 Pixels @ 043,027*/ 37, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 035,028*/ 1, 0x20, 0xFC, 
  /* RLE: 007 Pixels @ 036,028*/ 7, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 043,028*/ 1, 0x20, 0xFC, 
  /* RLE: 036 Pixels @ 044,028*/ 36, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 035,029*/ 1, 0x20, 0xFC, 
  /* RLE: 008 Pixels @ 036,029*/ 8, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 044,029*/ 1, 0x20, 0xFC, 
  /* RLE: 035 Pixels @ 000,030*/ 35, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 035,030*/ 1, 0x20, 0xFC, 
  /* RLE: 008 Pixels @ 036,030*/ 8, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 044,030*/ 1, 0x20, 0xFC, 
  /* RLE: 035 Pixels @ 000,031*/ 35, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 035,031*/ 1, 0x20, 0xFC, 
  /* RLE: 005 Pixels @ 036,031*/ 5, 0x45, 0x21, 
  /* RLE: 003 Pixels @ 041,031*/ 3, 0x20, 0xFC, 
  /* RLE: 001 Pixels @ 044,031*/ 1, 0x45, 0x21, 


  0};  /* 321 for 1440 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmicon_dc_rms_fs = {
  45, /* XSize */
  32, /* YSize */
  90, /* BytesPerLine */
  16, /* BitsPerPixel */
  (unsigned char *)acicon_dc_rms_fs,  /* Pointer to picture data */
  NULL  /* Pointer to palette */
 ,GUI_DRAW_RLEM16
};

/* *** End of file *** */
