/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.96.
*        Compiled Jul 19 2005, 13:50:35
*          (c) 2002-2005  Micrium, Inc.
  www.micrium.com

  (c) 1998-2005  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: icon_ac_rms_fs
* Dimensions:  45 * 32
* NumColors:   0
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif


static GUI_CONST_STORAGE unsigned char acicon_ac_rms_fs[] = {
  /* RLE: 152 Pixels @ 000,000*/ 152, 0x45, 0x21, 
  /* RLE: 003 Pixels @ 017,003*/ 3, 0x59, 0xCE, 
  /* RLE: 041 Pixels @ 020,003*/ 41, 0x45, 0x21, 
  /* ABS: 005 Pixels @ 016,004*/ 0, 5, 0x59, 0xCE, 0x45, 0x21, 0x45, 0x21, 0x45, 0x21, 0x59, 0xCE, 
  /* RLE: 040 Pixels @ 021,004*/ 40, 0x45, 0x21, 
  /* ABS: 005 Pixels @ 016,005*/ 0, 5, 0x59, 0xCE, 0x45, 0x21, 0x45, 0x21, 0x45, 0x21, 0x59, 0xCE, 
  /* RLE: 033 Pixels @ 021,005*/ 33, 0x45, 0x21, 
  /* ABS: 025 Pixels @ 009,006*/ 0, 25, 0x20, 0xFC, 0x45, 0x21, 0x45, 0x21, 0x20, 0xFC, 0x20, 0xFC, 0x45, 0x21, 0x59, 0xCE, 0x45, 0x21, 0x20, 0xFC, 0x20, 0xFC, 0x20, 0xFC, 0x45, 0x21, 0x59, 0xCE, 0x45, 0x21, 0x20, 0xFC, 0x20, 0xFC, 0x45, 0x21, 
        0x20, 0xFC, 0x20, 0xFC, 0x45, 0x21, 0x20, 0xFC, 0x20, 0xFC, 0x45, 0x21, 0x20, 0xFC, 0x20, 0xFC, 
  /* RLE: 019 Pixels @ 034,006*/ 19, 0x45, 0x21, 
  /* RLE: 003 Pixels @ 008,007*/ 3, 0x20, 0xFC, 
  /* RLE: 004 Pixels @ 011,007*/ 4, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 015,007*/ 1, 0x59, 0xCE, 
  /* RLE: 005 Pixels @ 016,007*/ 5, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 021,007*/ 1, 0x59, 0xCE, 
  /* RLE: 030 Pixels @ 022,007*/ 30, 0x45, 0x21, 
  /* RLE: 005 Pixels @ 007,008*/ 5, 0x20, 0xFC, 
  /* RLE: 003 Pixels @ 012,008*/ 3, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 015,008*/ 1, 0x59, 0xCE, 
  /* RLE: 005 Pixels @ 016,008*/ 5, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 021,008*/ 1, 0x59, 0xCE, 
  /* RLE: 032 Pixels @ 022,008*/ 32, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 009,009*/ 1, 0x20, 0xFC, 
  /* RLE: 004 Pixels @ 010,009*/ 4, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 014,009*/ 1, 0x59, 0xCE, 
  /* RLE: 007 Pixels @ 015,009*/ 7, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 022,009*/ 1, 0x59, 0xCE, 
  /* RLE: 031 Pixels @ 023,009*/ 31, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 009,010*/ 1, 0x20, 0xFC, 
  /* RLE: 004 Pixels @ 010,010*/ 4, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 014,010*/ 1, 0x59, 0xCE, 
  /* RLE: 007 Pixels @ 015,010*/ 7, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 022,010*/ 1, 0x59, 0xCE, 
  /* RLE: 031 Pixels @ 023,010*/ 31, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 009,011*/ 1, 0x20, 0xFC, 
  /* RLE: 004 Pixels @ 010,011*/ 4, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 014,011*/ 1, 0x59, 0xCE, 
  /* RLE: 007 Pixels @ 015,011*/ 7, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 022,011*/ 1, 0x59, 0xCE, 
  /* RLE: 029 Pixels @ 023,011*/ 29, 0x45, 0x21, 
  /* RLE: 005 Pixels @ 007,012*/ 5, 0x20, 0xFC, 
  /* ABS: 003 Pixels @ 012,012*/ 0, 3, 0x45, 0x21, 0x45, 0x21, 0x59, 0xCE, 
  /* RLE: 007 Pixels @ 015,012*/ 7, 0x45, 0x21, 
  /* ABS: 002 Pixels @ 022,012*/ 0, 2, 0x59, 0xCE, 0x59, 0xCE, 
  /* RLE: 007 Pixels @ 024,012*/ 7, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 031,012*/ 1, 0x59, 0xCE, 
  /* RLE: 036 Pixels @ 032,012*/ 36, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 023,013*/ 1, 0x59, 0xCE, 
  /* RLE: 007 Pixels @ 024,013*/ 7, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 031,013*/ 1, 0x59, 0xCE, 
  /* RLE: 036 Pixels @ 032,013*/ 36, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 023,014*/ 1, 0x59, 0xCE, 
  /* RLE: 007 Pixels @ 024,014*/ 7, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 031,014*/ 1, 0x59, 0xCE, 
  /* RLE: 036 Pixels @ 032,014*/ 36, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 023,015*/ 1, 0x59, 0xCE, 
  /* RLE: 007 Pixels @ 024,015*/ 7, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 031,015*/ 1, 0x59, 0xCE, 
  /* RLE: 037 Pixels @ 032,015*/ 37, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 024,016*/ 1, 0x59, 0xCE, 
  /* RLE: 005 Pixels @ 025,016*/ 5, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 030,016*/ 1, 0x59, 0xCE, 
  /* RLE: 038 Pixels @ 031,016*/ 38, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 024,017*/ 1, 0x59, 0xCE, 
  /* RLE: 005 Pixels @ 025,017*/ 5, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 030,017*/ 1, 0x59, 0xCE, 
  /* RLE: 038 Pixels @ 031,017*/ 38, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 024,018*/ 1, 0x59, 0xCE, 
  /* RLE: 005 Pixels @ 025,018*/ 5, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 030,018*/ 1, 0x59, 0xCE, 
  /* RLE: 039 Pixels @ 031,018*/ 39, 0x45, 0x21, 
  /* ABS: 005 Pixels @ 025,019*/ 0, 5, 0x59, 0xCE, 0x45, 0x21, 0x45, 0x21, 0x45, 0x21, 0x59, 0xCE, 
  /* RLE: 040 Pixels @ 030,019*/ 40, 0x45, 0x21, 
  /* ABS: 005 Pixels @ 025,020*/ 0, 5, 0x59, 0xCE, 0x45, 0x21, 0x45, 0x21, 0x45, 0x21, 0x59, 0xCE, 
  /* RLE: 041 Pixels @ 030,020*/ 41, 0x45, 0x21, 
  /* RLE: 003 Pixels @ 026,021*/ 3, 0x59, 0xCE, 
  /* RLE: 141 Pixels @ 029,021*/ 141, 0x45, 0x21, 
  /* RLE: 004 Pixels @ 035,024*/ 4, 0x20, 0xFC, 
  /* RLE: 003 Pixels @ 039,024*/ 3, 0x45, 0x21, 
  /* RLE: 003 Pixels @ 042,024*/ 3, 0x20, 0xFC, 
  /* RLE: 035 Pixels @ 000,025*/ 35, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 035,025*/ 1, 0x20, 0xFC, 
  /* RLE: 005 Pixels @ 036,025*/ 5, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 041,025*/ 1, 0x20, 0xFC, 
  /* RLE: 038 Pixels @ 042,025*/ 38, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 035,026*/ 1, 0x20, 0xFC, 
  /* RLE: 005 Pixels @ 036,026*/ 5, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 041,026*/ 1, 0x20, 0xFC, 
  /* RLE: 038 Pixels @ 042,026*/ 38, 0x45, 0x21, 
  /* RLE: 004 Pixels @ 035,027*/ 4, 0x20, 0xFC, 
  /* RLE: 003 Pixels @ 039,027*/ 3, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 042,027*/ 1, 0x20, 0xFC, 
  /* RLE: 037 Pixels @ 043,027*/ 37, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 035,028*/ 1, 0x20, 0xFC, 
  /* RLE: 007 Pixels @ 036,028*/ 7, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 043,028*/ 1, 0x20, 0xFC, 
  /* RLE: 036 Pixels @ 044,028*/ 36, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 035,029*/ 1, 0x20, 0xFC, 
  /* RLE: 008 Pixels @ 036,029*/ 8, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 044,029*/ 1, 0x20, 0xFC, 
  /* RLE: 035 Pixels @ 000,030*/ 35, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 035,030*/ 1, 0x20, 0xFC, 
  /* RLE: 008 Pixels @ 036,030*/ 8, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 044,030*/ 1, 0x20, 0xFC, 
  /* RLE: 035 Pixels @ 000,031*/ 35, 0x45, 0x21, 
  /* RLE: 001 Pixels @ 035,031*/ 1, 0x20, 0xFC, 
  /* RLE: 005 Pixels @ 036,031*/ 5, 0x45, 0x21, 
  /* RLE: 003 Pixels @ 041,031*/ 3, 0x20, 0xFC, 
  /* RLE: 001 Pixels @ 044,031*/ 1, 0x45, 0x21, 


  0};  /* 266 for 1440 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmicon_ac_rms_fs = {
  45, /* XSize */
  32, /* YSize */
  90, /* BytesPerLine */
  16, /* BitsPerPixel */
  (unsigned char *)acicon_ac_rms_fs,  /* Pointer to picture data */
  NULL  /* Pointer to palette */
 ,GUI_DRAW_RLEM16
};

/* *** End of file *** */
