/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.96.
*        Compiled Jul 19 2005, 13:50:35
*          (c) 2002-2005  Micrium, Inc.
  www.micrium.com

  (c) 1998-2005  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: softkeyKnobOff
* Dimensions:  17 * 14
* NumColors:   0
*
**********************************************************************
*/

#include "stdlib.h"

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif


static GUI_CONST_STORAGE unsigned char acsoftkeyKnobOff[] = {
  /* RLE: 018 Pixels @ 000,000*/ 18, 0xCB, 0x52, 
  /* RLE: 007 Pixels @ 001,001*/ 7, 0xCB, 0x52, 
  /* RLE: 004 Pixels @ 008,001*/ 4, 0x6D, 0x6B, 
  /* RLE: 004 Pixels @ 012,001*/ 4, 0xCB, 0x52, 
  /* ABS: 002 Pixels @ 016,001*/ 0, 2, 0xCB, 0x52, 0xCB, 0x52, 
  /* RLE: 011 Pixels @ 001,002*/ 11, 0xCB, 0x52, 
  /* ABS: 006 Pixels @ 012,002*/ 0, 6, 0x6D, 0x6B, 0x6D, 0x6B, 0xCB, 0x52, 0xCB, 0x52, 0xCB, 0x52, 0xCB, 0x52, 
  /* RLE: 013 Pixels @ 001,003*/ 13, 0xCB, 0x52, 
  /* ABS: 007 Pixels @ 014,003*/ 0, 7, 0x6D, 0x6B, 0xCB, 0x52, 0xCB, 0x52, 0xCB, 0x52, 0xCB, 0x52, 0xCB, 0x52, 0x6D, 0x6B, 
  /* RLE: 010 Pixels @ 004,004*/ 10, 0xCB, 0x52, 
  /* ABS: 008 Pixels @ 014,004*/ 0, 8, 0x6D, 0x6B, 0xCB, 0x52, 0xCB, 0x52, 0xCB, 0x52, 0xCB, 0x52, 0x6D, 0x6B, 0x6D, 0x6B, 0x6D, 0x6B, 
  /* RLE: 010 Pixels @ 005,005*/ 10, 0xCB, 0x52, 
  /* ABS: 003 Pixels @ 015,005*/ 0, 3, 0x6D, 0x6B, 0xCB, 0x52, 0xCB, 0x52, 
  /* RLE: 005 Pixels @ 001,006*/ 5, 0x6D, 0x6B, 
  /* RLE: 009 Pixels @ 006,006*/ 9, 0xCB, 0x52, 
  /* ABS: 006 Pixels @ 015,006*/ 0, 6, 0x6D, 0x6B, 0xCB, 0x52, 0xCB, 0x52, 0xCB, 0x52, 0xCB, 0x52, 0x6D, 0x6B, 
  /* RLE: 011 Pixels @ 004,007*/ 11, 0xCB, 0x52, 
  /* ABS: 006 Pixels @ 015,007*/ 0, 6, 0x6D, 0x6B, 0xCB, 0x52, 0xCB, 0x52, 0xCB, 0x52, 0xCB, 0x52, 0x6D, 0x6B, 
  /* RLE: 011 Pixels @ 004,008*/ 11, 0xCB, 0x52, 
  /* ABS: 007 Pixels @ 015,008*/ 0, 7, 0x6D, 0x6B, 0xCB, 0x52, 0xCB, 0x52, 0xCB, 0x52, 0xCB, 0x52, 0xCB, 0x52, 0x6D, 0x6B, 
  /* RLE: 009 Pixels @ 005,009*/ 9, 0xCB, 0x52, 
  /* ABS: 008 Pixels @ 014,009*/ 0, 8, 0x6D, 0x6B, 0xCB, 0x52, 0xCB, 0x52, 0xCB, 0x52, 0xCB, 0x52, 0xCB, 0x52, 0xCB, 0x52, 0x6D, 0x6B, 
  /* RLE: 009 Pixels @ 005,010*/ 9, 0xCB, 0x52, 
  /* ABS: 004 Pixels @ 014,010*/ 0, 4, 0x6D, 0x6B, 0xCB, 0x52, 0xCB, 0x52, 0xCB, 0x52, 
  /* RLE: 004 Pixels @ 001,011*/ 4, 0xCB, 0x52, 
  /* ABS: 002 Pixels @ 005,011*/ 0, 2, 0x6D, 0x6B, 0x6D, 0x6B, 
  /* RLE: 005 Pixels @ 007,011*/ 5, 0xCB, 0x52, 
  /* ABS: 006 Pixels @ 012,011*/ 0, 6, 0x6D, 0x6B, 0x6D, 0x6B, 0xCB, 0x52, 0xCB, 0x52, 0xCB, 0x52, 0xCB, 0x52, 
  /* RLE: 006 Pixels @ 001,012*/ 6, 0xCB, 0x52, 
  /* RLE: 005 Pixels @ 007,012*/ 5, 0x6D, 0x6B, 
  /* RLE: 004 Pixels @ 012,012*/ 4, 0xCB, 0x52, 
  /* RLE: 018 Pixels @ 016,012*/ 18, 0xCB, 0x52, 


  0};  /* 129 for 238 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmSoftKeyKnobOff = {
  17, /* XSize */
  14, /* YSize */
  34, /* BytesPerLine */
  16, /* BitsPerPixel */
  (unsigned char *)acsoftkeyKnobOff,  /* Pointer to picture data */
  NULL  /* Pointer to palette */
 ,GUI_DRAW_RLEM16
};

/* *** End of file *** */
